//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PlantafelNAV.ws_arbeitsplatzservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_Arbeitzplatz_Binding", Namespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz")]
    public partial class WS_Arbeitzplatz_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Arbeitzplatz_Service() {
            this.Url = global::PlantafelNAV.Properties.Settings.Default.PlantafelNAV_ws_arbeitsplatzservice_WS_Arbeitzplatz_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WS_Arbeitzplatz")]
        public WS_Arbeitzplatz Read(string Routing_No, string Version_Code, string Operation_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Routing_No,
                        Version_Code,
                        Operation_No});
            return ((WS_Arbeitzplatz)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Routing_No, string Version_Code, string Operation_No) {
            this.ReadAsync(Routing_No, Version_Code, Operation_No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Routing_No, string Version_Code, string Operation_No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Routing_No,
                        Version_Code,
                        Operation_No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WS_Arbeitzplatz")]
        public WS_Arbeitzplatz ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((WS_Arbeitzplatz)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WS_Arbeitzplatz[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] WS_Arbeitzplatz_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((WS_Arbeitzplatz[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(WS_Arbeitzplatz_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(WS_Arbeitzplatz_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref WS_Arbeitzplatz WS_Arbeitzplatz) {
            object[] results = this.Invoke("Create", new object[] {
                        WS_Arbeitzplatz});
            WS_Arbeitzplatz = ((WS_Arbeitzplatz)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(WS_Arbeitzplatz WS_Arbeitzplatz) {
            this.CreateAsync(WS_Arbeitzplatz, null);
        }
        
        /// <remarks/>
        public void CreateAsync(WS_Arbeitzplatz WS_Arbeitzplatz, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        WS_Arbeitzplatz}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref WS_Arbeitzplatz[] WS_Arbeitzplatz_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        WS_Arbeitzplatz_List});
            WS_Arbeitzplatz_List = ((WS_Arbeitzplatz[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(WS_Arbeitzplatz[] WS_Arbeitzplatz_List) {
            this.CreateMultipleAsync(WS_Arbeitzplatz_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(WS_Arbeitzplatz[] WS_Arbeitzplatz_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        WS_Arbeitzplatz_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref WS_Arbeitzplatz WS_Arbeitzplatz) {
            object[] results = this.Invoke("Update", new object[] {
                        WS_Arbeitzplatz});
            WS_Arbeitzplatz = ((WS_Arbeitzplatz)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(WS_Arbeitzplatz WS_Arbeitzplatz) {
            this.UpdateAsync(WS_Arbeitzplatz, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(WS_Arbeitzplatz WS_Arbeitzplatz, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        WS_Arbeitzplatz}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref WS_Arbeitzplatz[] WS_Arbeitzplatz_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        WS_Arbeitzplatz_List});
            WS_Arbeitzplatz_List = ((WS_Arbeitzplatz[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(WS_Arbeitzplatz[] WS_Arbeitzplatz_List) {
            this.UpdateMultipleAsync(WS_Arbeitzplatz_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(WS_Arbeitzplatz[] WS_Arbeitzplatz_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        WS_Arbeitzplatz_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz")]
    public partial class WS_Arbeitzplatz {
        
        private string keyField;
        
        private string routing_NoField;
        
        private string version_CodeField;
        
        private string operation_NoField;
        
        private string next_Operation_NoField;
        
        private string previous_Operation_NoField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string work_Center_NoField;
        
        private string work_Center_Group_CodeField;
        
        private string descriptionField;
        
        private decimal setup_TimeField;
        
        private bool setup_TimeFieldSpecified;
        
        private decimal run_TimeField;
        
        private bool run_TimeFieldSpecified;
        
        private decimal wait_TimeField;
        
        private bool wait_TimeFieldSpecified;
        
        private decimal move_TimeField;
        
        private bool move_TimeFieldSpecified;
        
        private decimal fixed_Scrap_QuantityField;
        
        private bool fixed_Scrap_QuantityFieldSpecified;
        
        private decimal lot_SizeField;
        
        private bool lot_SizeFieldSpecified;
        
        private decimal scrap_Factor_PercentField;
        
        private bool scrap_Factor_PercentFieldSpecified;
        
        private string setup_Time_Unit_of_Meas_CodeField;
        
        private string run_Time_Unit_of_Meas_CodeField;
        
        private string wait_Time_Unit_of_Meas_CodeField;
        
        private string move_Time_Unit_of_Meas_CodeField;
        
        private decimal minimum_Process_TimeField;
        
        private bool minimum_Process_TimeFieldSpecified;
        
        private decimal maximum_Process_TimeField;
        
        private bool maximum_Process_TimeFieldSpecified;
        
        private decimal concurrent_CapacitiesField;
        
        private bool concurrent_CapacitiesFieldSpecified;
        
        private decimal send_Ahead_QuantityField;
        
        private bool send_Ahead_QuantityFieldSpecified;
        
        private string routing_Link_CodeField;
        
        private string standard_Task_CodeField;
        
        private decimal unit_Cost_perField;
        
        private bool unit_Cost_perFieldSpecified;
        
        private bool recalculateField;
        
        private bool recalculateFieldSpecified;
        
        private bool commentField;
        
        private bool commentFieldSpecified;
        
        private int sequence_No_ForwardField;
        
        private bool sequence_No_ForwardFieldSpecified;
        
        private int sequence_No_BackwardField;
        
        private bool sequence_No_BackwardFieldSpecified;
        
        private decimal fixed_Scrap_Qty_AccumField;
        
        private bool fixed_Scrap_Qty_AccumFieldSpecified;
        
        private decimal scrap_Factor_Percent_AccumulatedField;
        
        private bool scrap_Factor_Percent_AccumulatedFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Routing_No {
            get {
                return this.routing_NoField;
            }
            set {
                this.routing_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Version_Code {
            get {
                return this.version_CodeField;
            }
            set {
                this.version_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Operation_No {
            get {
                return this.operation_NoField;
            }
            set {
                this.operation_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Next_Operation_No {
            get {
                return this.next_Operation_NoField;
            }
            set {
                this.next_Operation_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Previous_Operation_No {
            get {
                return this.previous_Operation_NoField;
            }
            set {
                this.previous_Operation_NoField = value;
            }
        }
        
        /// <remarks/>
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Work_Center_No {
            get {
                return this.work_Center_NoField;
            }
            set {
                this.work_Center_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Work_Center_Group_Code {
            get {
                return this.work_Center_Group_CodeField;
            }
            set {
                this.work_Center_Group_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Setup_Time {
            get {
                return this.setup_TimeField;
            }
            set {
                this.setup_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Setup_TimeSpecified {
            get {
                return this.setup_TimeFieldSpecified;
            }
            set {
                this.setup_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Run_Time {
            get {
                return this.run_TimeField;
            }
            set {
                this.run_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Run_TimeSpecified {
            get {
                return this.run_TimeFieldSpecified;
            }
            set {
                this.run_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Wait_Time {
            get {
                return this.wait_TimeField;
            }
            set {
                this.wait_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Wait_TimeSpecified {
            get {
                return this.wait_TimeFieldSpecified;
            }
            set {
                this.wait_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Move_Time {
            get {
                return this.move_TimeField;
            }
            set {
                this.move_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Move_TimeSpecified {
            get {
                return this.move_TimeFieldSpecified;
            }
            set {
                this.move_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Fixed_Scrap_Quantity {
            get {
                return this.fixed_Scrap_QuantityField;
            }
            set {
                this.fixed_Scrap_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fixed_Scrap_QuantitySpecified {
            get {
                return this.fixed_Scrap_QuantityFieldSpecified;
            }
            set {
                this.fixed_Scrap_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Lot_Size {
            get {
                return this.lot_SizeField;
            }
            set {
                this.lot_SizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Lot_SizeSpecified {
            get {
                return this.lot_SizeFieldSpecified;
            }
            set {
                this.lot_SizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Scrap_Factor_Percent {
            get {
                return this.scrap_Factor_PercentField;
            }
            set {
                this.scrap_Factor_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Scrap_Factor_PercentSpecified {
            get {
                return this.scrap_Factor_PercentFieldSpecified;
            }
            set {
                this.scrap_Factor_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Setup_Time_Unit_of_Meas_Code {
            get {
                return this.setup_Time_Unit_of_Meas_CodeField;
            }
            set {
                this.setup_Time_Unit_of_Meas_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Run_Time_Unit_of_Meas_Code {
            get {
                return this.run_Time_Unit_of_Meas_CodeField;
            }
            set {
                this.run_Time_Unit_of_Meas_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Wait_Time_Unit_of_Meas_Code {
            get {
                return this.wait_Time_Unit_of_Meas_CodeField;
            }
            set {
                this.wait_Time_Unit_of_Meas_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Move_Time_Unit_of_Meas_Code {
            get {
                return this.move_Time_Unit_of_Meas_CodeField;
            }
            set {
                this.move_Time_Unit_of_Meas_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Minimum_Process_Time {
            get {
                return this.minimum_Process_TimeField;
            }
            set {
                this.minimum_Process_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Minimum_Process_TimeSpecified {
            get {
                return this.minimum_Process_TimeFieldSpecified;
            }
            set {
                this.minimum_Process_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Maximum_Process_Time {
            get {
                return this.maximum_Process_TimeField;
            }
            set {
                this.maximum_Process_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_Process_TimeSpecified {
            get {
                return this.maximum_Process_TimeFieldSpecified;
            }
            set {
                this.maximum_Process_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Concurrent_Capacities {
            get {
                return this.concurrent_CapacitiesField;
            }
            set {
                this.concurrent_CapacitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Concurrent_CapacitiesSpecified {
            get {
                return this.concurrent_CapacitiesFieldSpecified;
            }
            set {
                this.concurrent_CapacitiesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Send_Ahead_Quantity {
            get {
                return this.send_Ahead_QuantityField;
            }
            set {
                this.send_Ahead_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Send_Ahead_QuantitySpecified {
            get {
                return this.send_Ahead_QuantityFieldSpecified;
            }
            set {
                this.send_Ahead_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Routing_Link_Code {
            get {
                return this.routing_Link_CodeField;
            }
            set {
                this.routing_Link_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Standard_Task_Code {
            get {
                return this.standard_Task_CodeField;
            }
            set {
                this.standard_Task_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Cost_per {
            get {
                return this.unit_Cost_perField;
            }
            set {
                this.unit_Cost_perField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_Cost_perSpecified {
            get {
                return this.unit_Cost_perFieldSpecified;
            }
            set {
                this.unit_Cost_perFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Recalculate {
            get {
                return this.recalculateField;
            }
            set {
                this.recalculateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecalculateSpecified {
            get {
                return this.recalculateFieldSpecified;
            }
            set {
                this.recalculateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentSpecified {
            get {
                return this.commentFieldSpecified;
            }
            set {
                this.commentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Sequence_No_Forward {
            get {
                return this.sequence_No_ForwardField;
            }
            set {
                this.sequence_No_ForwardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sequence_No_ForwardSpecified {
            get {
                return this.sequence_No_ForwardFieldSpecified;
            }
            set {
                this.sequence_No_ForwardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Sequence_No_Backward {
            get {
                return this.sequence_No_BackwardField;
            }
            set {
                this.sequence_No_BackwardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sequence_No_BackwardSpecified {
            get {
                return this.sequence_No_BackwardFieldSpecified;
            }
            set {
                this.sequence_No_BackwardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Fixed_Scrap_Qty_Accum {
            get {
                return this.fixed_Scrap_Qty_AccumField;
            }
            set {
                this.fixed_Scrap_Qty_AccumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fixed_Scrap_Qty_AccumSpecified {
            get {
                return this.fixed_Scrap_Qty_AccumFieldSpecified;
            }
            set {
                this.fixed_Scrap_Qty_AccumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Scrap_Factor_Percent_Accumulated {
            get {
                return this.scrap_Factor_Percent_AccumulatedField;
            }
            set {
                this.scrap_Factor_Percent_AccumulatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Scrap_Factor_Percent_AccumulatedSpecified {
            get {
                return this.scrap_Factor_Percent_AccumulatedFieldSpecified;
            }
            set {
                this.scrap_Factor_Percent_AccumulatedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz")]
    public enum Type {
        
        /// <remarks/>
        Work_Center,
        
        /// <remarks/>
        Machine_Center,
        
        /// <remarks/>
        _blank_,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz")]
    public partial class WS_Arbeitzplatz_Filter {
        
        private WS_Arbeitzplatz_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public WS_Arbeitzplatz_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_arbeitzplatz")]
    public enum WS_Arbeitzplatz_Fields {
        
        /// <remarks/>
        Routing_No,
        
        /// <remarks/>
        Version_Code,
        
        /// <remarks/>
        Operation_No,
        
        /// <remarks/>
        Next_Operation_No,
        
        /// <remarks/>
        Previous_Operation_No,
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Work_Center_No,
        
        /// <remarks/>
        Work_Center_Group_Code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Setup_Time,
        
        /// <remarks/>
        Run_Time,
        
        /// <remarks/>
        Wait_Time,
        
        /// <remarks/>
        Move_Time,
        
        /// <remarks/>
        Fixed_Scrap_Quantity,
        
        /// <remarks/>
        Lot_Size,
        
        /// <remarks/>
        Scrap_Factor_Percent,
        
        /// <remarks/>
        Setup_Time_Unit_of_Meas_Code,
        
        /// <remarks/>
        Run_Time_Unit_of_Meas_Code,
        
        /// <remarks/>
        Wait_Time_Unit_of_Meas_Code,
        
        /// <remarks/>
        Move_Time_Unit_of_Meas_Code,
        
        /// <remarks/>
        Minimum_Process_Time,
        
        /// <remarks/>
        Maximum_Process_Time,
        
        /// <remarks/>
        Concurrent_Capacities,
        
        /// <remarks/>
        Send_Ahead_Quantity,
        
        /// <remarks/>
        Routing_Link_Code,
        
        /// <remarks/>
        Standard_Task_Code,
        
        /// <remarks/>
        Unit_Cost_per,
        
        /// <remarks/>
        Recalculate,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Sequence_No_Forward,
        
        /// <remarks/>
        Sequence_No_Backward,
        
        /// <remarks/>
        Fixed_Scrap_Qty_Accum,
        
        /// <remarks/>
        Scrap_Factor_Percent_Accumulated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_Arbeitzplatz Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_Arbeitzplatz)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_Arbeitzplatz Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_Arbeitzplatz)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_Arbeitzplatz[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_Arbeitzplatz[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_Arbeitzplatz WS_Arbeitzplatz {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_Arbeitzplatz)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_Arbeitzplatz[] WS_Arbeitzplatz_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_Arbeitzplatz[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_Arbeitzplatz WS_Arbeitzplatz {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_Arbeitzplatz)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_Arbeitzplatz[] WS_Arbeitzplatz_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_Arbeitzplatz[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591